version: '3'

services:
  device1:
    image: ghcr.io/sjohann81/labredes:latest
    container_name: device1
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/root/T1
    ports:
      - "8080:8080"
    networks:
      - lab-t1

  device2:
    image: ghcr.io/sjohann81/labredes:latest
    container_name: device2
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/root/T1
    ports:
      - "8081:8080"
    networks:
      - lab-t1

  device3:
    image: ghcr.io/sjohann81/labredes:latest
    container_name: device3
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/root/T1
    ports:
      - "8082:8080"
    networks:
      - lab-t1

networks:
  lab-t1: